import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeNav from '../Components/PageComp/HomeNav'
import Gallery from '../Components/PageComp/Gallery'
import NewWork from '../Components/PageComp/NewWork'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>
      <HomeNav/>
      <Gallery/>
      <NewWork/>
     </main>
    </div>
  )
}
